services:
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4
    container_name: lavalink
    restart: always
    environment:
      - _JAVA_OPTIONS=-Xmx512m
    volumes:
      - ./Lavalink/application.yml:/opt/Lavalink/application.yml
      - ./Lavalink/plugins:/opt/Lavalink/plugins
      - ./Lavalink/youtube-data:/opt/Lavalink/youtube-data
    ports:
      - "2333:2333"
    networks:
      - bot-network

  sambot:
    build: .
    container_name: sambot
    volumes:
      - .:/app
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - lavalink
    networks:
      - bot-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  bot-network:
    driver: bridge
